name: Publish

on:
  workflow_dispatch:
        
  schedule:
    - cron: "0 0 * * *"

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run release script
        working-directory: ./
        run: ./release.sh
